apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-servicemonitor
  namespace: sentiment-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sentiment-app
  namespaceSelector:
    matchNames:
      - sentiment-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
